language: php

php:
  - 7.0

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install --no-interaction

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml

